# Generated by Django 6.0 on 2025-12-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(help_text='Stok Kodu (Örn: KZK-MAVI-L)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Ürün Adı', max_length=255)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Son Alış Fiyatı')),
                ('weighted_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ortalama Maliyet')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Mevcut Stok')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='KDV Oranı (%)', max_digits=4)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
