# Generated by Django 6.0 on 2025-12-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marketplaces/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('SALES', 'Satış Raporu/Hakediş'), ('STOCK', 'Stok Envanter Raporu')], max_length=20)),
                ('excel_column_name', models.CharField(max_length=255)),
                ('db_field_name', models.CharField(max_length=255)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integrations.marketplace')),
            ],
            options={
                'verbose_name': 'Sütun Eşleştirmesi',
                'unique_together': {('marketplace', 'file_type', 'db_field_name')},
            },
        ),
    ]
