# Generated by Django 6.0 on 2025-12-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Satış'), ('RETURN', 'İade'), ('CANCEL', 'İptal')], max_length=10)),
                ('order_number', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Komisyon Tutarı')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kargo Maliyeti')),
                ('cost_at_transaction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='O anki Maliyet')),
                ('transaction_date', models.DateTimeField()),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.marketplace')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
