# Generated by Django 6.0 on 2025-12-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RENT', 'Kira'), ('SALARY', 'Maaş / Personel'), ('ELECTRICITY', 'Elektrik Faturası'), ('WATER', 'Su Faturası'), ('INTERNET', 'İnternet / Telefon'), ('LOAN', 'Kredi Ödemesi'), ('PREMIUM', 'Prim Ödemesi'), ('TAX', 'Vergi Ödemesi'), ('MARKETING', 'Reklam / Pazarlama'), ('OTHER', 'Diğer Genel Giderler')], max_length=20, verbose_name='Kategori')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('expense_date', models.DateField(verbose_name='Harcama Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Satış'), ('RETURN', 'İade'), ('CANCEL', 'İptal'), ('PURCHASE', 'Stok Alışı/Fatura')], max_length=10),
        ),
    ]
